### ISSUE TITLE
Sequence issue

### ISSUE THREAD

**Issue by benemanuel** [charlesLoder/hebrewTransliteration#1]
In cases of more then one vowel on a letter the sequence messes it up
eg: יְרְוּשָׁלִָֽם 
is sequeced as יְרְוּשָׁלִָֽם 
which is a mistake.
this is the two words in hex
`&#x05D9;&#x05B0;&#x05E8;&#x05B0;&#x05D5;&#x05BC;&#x05E9;&#x05C1;&#x05B8;&#x05DC;&#x05B8;&#x05BD;&#x05B4;&#x05DD;`
`&#x05D9;&#x05B0;&#x05E8;&#x05B0;&#x05D5;&#x05BC;&#x05E9;&#x05C1;&#x05B8;&#x05DC;&#x05B4;&#x05B8;&#x05BD;&#x05DD;`

**Comment by charlesLoder** [comment]
@benemanuel thanks!

I've moved this to [an issue in the repo](https://github.com/charlesLoder/hebrew-transliteration/issues/16) for the npm package that handles all the logic.

This current repo has essentially become a wrapper for the npm package
