### ISSUE TITLE
Transliteration error for עֲרְעֹור

### ISSUE THREAD

**Issue by BillMeyerRSA** [charlesLoder/hebrewTransliteration#51]
Is the output of this word correct? I used SBL Academic in this
עֲרְעֹור--> rǝʿăʿôr
I tested with other transliteration apps like https://www.alittlehebrew.com/transliterate/ and get totally different results with same schema.

**Comment by charlesLoder** [comment]
@BillMeyerRSA the output doesn't look right, but the word itself seems odd. I don't think I've ever seen a hateph-patach followed by a shewa.

Which text did you get this from?

The package that generates the transliteration does syllabification first, and that word can't be syllabified correctly

**Comment by BillMeyerRSA** [comment]
I got it from SIL list of names that gives Hebrew, Traditional and SIL transliteration. 
עֲרֹועֵרִי	ʿărôʿērî	Aroerite
עֲרֹועֵר	ʿărôʿēr	Aroer
עֲרְעֹור	ʿărǝʿôr	Aroer

**Comment by charlesLoder** [comment]
Do you have a link?

**Comment by BillMeyerRSA** [comment]
From the "Gk and Heb Names -Unicode.txt" in the SIL NameTrans package that I got from nicholas_bailey@sil.org:

\ukey Aroer.2
\hm עֲרְעֹור
\ht ʿărǝʿôr
\hrsv Aroer
\hes עֲרֹועֵר
\hest ʿărôʿēr
\hede town; territory of Reuben
\her JDG.11:26

I looked up the verse in Judges 11:26 and saw the word was rendered as וּבְעַרְע֣וֹר (and in Aroer).

**Comment by charlesLoder** [comment]
That just looks like bad data then.

When I try וּבְעַרְע֣וֹר it is correctly _ûbǝʿarʿôr_, or without the prefixes as  _ʿarʿôr_.

But עֲרְעֹור is definitely a form that can't exist with that pointing

**Comment by BillMeyerRSA** [comment]
You solved a mystery for me there. My Hebrew is not on the advanced level where I could pick that up.

**Comment by BillMeyerRSA** [comment]
Great program btw. Will be using the NPM package in another program. 
Would love to have ISO 259-2 and some other schemas available.

**Comment by charlesLoder** [comment]
> Great program btw. Will be using the NPM package in another program. Would love to have ISO 259-2 and some other schemas available.

Great idea!

I added an issue to add [ISO 259](https://github.com/charlesLoder/hebrewTransliteration/issues/52).

The schemas aren't available in the NPM package itself (only on the site), but I think it could be a good idea to make them available in the package as well. I made an [issue for that](https://github.com/charlesLoder/hebrew-transliteration/issues/25) as well
