### ISSUE TITLE
Divine name dropping latin char after

### ISSUE THREAD

**Issue by charlesLoder** [charlesLoder/hebrewTransliteration#55]
See [here](https://github.com/charlesLoder/hebrewTransliteration/issues/53#issuecomment-1239252649)

The Latin character after the Divine Name is dropped

Hebrew
```
כִּי אִם בְּתוֹרַת יְהוָה, חֶפְצוֹ; וּבְתוֹרָתוֹ יֶהְגֶּה, יוֹמָם וָלָיְלָה
```

Transliteration
```
kî ʾim bǝtôrat yhwh ḥepṣô; ûbǝtôrātô yehgê, yômām wālāyǝlâ
```

**Comment by charlesLoder** [comment]
Should have made it in the havarot package

**Comment by BillMeyerRSA** [comment]
> ```
> כִּי אִם בְּתוֹרַת יְהוָה, חֶפְצוֹ; וּבְתוֹרָתוֹ יֶהְגֶּה, יוֹמָם וָלָיְלָה
> ```

I tried this phrase again in the online App and got this result:
kî ʾim bǝ-yhwh ḥep̱ṣōûḇǝṯôrāṯôyehgê;, yômāmwālāyǝlâ
kî ʾīm bᵉ-yhwh ḥęp̄ṣōûḇᵉṯôrāṯôyęhgę̄;, yômāmwālāyᵉlâ

**Comment by charlesLoder** [comment]
I see what happened. The latest [PR on the syllabification package](https://github.com/charlesLoder/havarotjs/pull/62) fixes it. The next version, 2.1.2, should have the changes

**Comment by charlesLoder** [comment]
Ugh, I'm all over the place on this one.

For the input text:

```
כִּי אִם בְּתוֹרַת יְהוָה, חֶפְצוֹ; וּבְתוֹרָתוֹ יֶהְגֶּה, יוֹמָם וָלָיְלָה
```

✅ The latest version of `2.1.2` of the hebrew-transliteration package, fixes this output

From:
```txt
kî ʾim bǝyhwh ḥep̱ṣōûḇǝṯôrāṯôyehgê;, yômāmwālāyǝlâ
```

To:
```txt
kî ʾim bǝtôrat yhwh ḥepṣô; ûbǝtôrātô yehgê, yômām wālāyǝlâ
```

❌ But, the comma after the Divine Name is still missing

Will create an issue int he hebrew-transliteration repo
