### ISSUE TITLE
Use list of schema json files to populate dropdown

### ISSUE THREAD

**Issue by BillMeyerRSA** [charlesLoder/hebrewTransliteration#64]
Instead of hardcoding the list of transliteration schemas available, populate from the list of schema json files present in the directory. 
And when a new schema is uploaded, place in the directory where it can be detected. Maybe add field in the json file for description of the schema.

**Comment by charlesLoder** [comment]
That's a good idea.

I can even populate them from the packages `schemas` export.

**Comment by BillMeyerRSA** [comment]
Maybe split or filtered list. On top the default list of schemas, separator, and then the user contributed schemas.

**Comment by BillMeyerRSA** [comment]
The latest iteration seems to be easier to use. 
Basically adding the schema json files and adding to config.json to populate the dropdown list. 
When I tried it on a previous version there was quite a number of places to modify to get another schema added to the dropdown list. 
Thanks for the improvement.
