### ISSUE TITLE
JSS schema

### ISSUE THREAD

**Issue by camilstaps** [charlesLoder/hebrewTransliteration#71]
I was wondering if the following schema could be added. It approximates the guidelines in the [Journal of Semitic Studies stylesheet](https://static.primary.prod.gcms.the-infra.com/static/site/jss/document/Journal_of_Semitic_Studies_Style_Sheet_2023.pdf?node=e4a43e210123e8c82f97) as far as possible.

- I don't think it's possible to recognize short/long vowels(?) to distinguish e.g. *i* and *ī*, so I used *ī* for hireq-yod and *i* for plain hireq, which may require some manual fixes from the user (what would be helpful for this is a separate field for hireq+meteg and qibbuts+meteg).
- The style guide also prescribes that qamets before hatef qamets be transliterated as long qamets: בַּֽצָּהֳרָֽיִם should be *baṣṣ**å̄**hå̆rå̄yim*, not *baṣṣ**å**hå̆rå̄yim*. I am not sure if this can be specified in the current system.
- Tsere-he is not recognized correctly, I'm not sure why: וְהִנֵּ֥ה should be *wǝhinn**ē***, not *wǝhinn**ɛ***.

Some characters are not displayed well on my system. Would you be opposed to adding the `Brill` font as an option after Charis SIL but before Times New Roman for the output text area? Here is what I see now (with Times New Roman) vs with Brill:

![2023-06-13-102217_1260x102](https://github.com/charlesLoder/hebrewTransliteration/assets/1202754/1f6b5f2c-986e-46c0-b281-1b58196f2047)

![2023-06-13-102200_1254x51](https://github.com/charlesLoder/hebrewTransliteration/assets/1202754/ef3ac018-d90a-4359-8553-1d64048142a1)

```json
{
  "VOCAL_SHEVA": "ǝ",
  "HATAF_SEGOL": "ɛ̆",
  "HATAF_PATAH": "ă",
  "HATAF_QAMATS": "å̆",
  "HIRIQ": "i",
  "TSERE": "ē",
  "SEGOL": "ɛ",
  "PATAH": "a",
  "QAMATS": "å̄",
  "HOLAM": "ō",
  "QUBUTS": "u",
  "DAGESH": "",
  "DAGESH_CHAZAQ": true,
  "MAQAF": " ",
  "PASEQ": "",
  "SOF_PASUQ": "",
  "QAMATS_QATAN": "å",
  "FURTIVE_PATAH": "a",
  "HIRIQ_YOD": "ī",
  "TSERE_YOD": "ē",
  "SEGOL_YOD": "ɛ",
  "SHUREQ": "ū",
  "HOLAM_VAV": "ō",
  "QAMATS_HE": "å̄",
  "SEGOL_HE": "ɛ",
  "TSERE_HE": "ē",
  "MS_SUFX": "å̄yw",
  "ALEF": "ʾ",
  "BET_DAGESH": "b",
  "BET": "ḇ",
  "GIMEL": "ḡ",
  "GIMEL_DAGESH": "g",
  "DALET": "ḏ",
  "DALET_DAGESH": "d",
  "HE": "h",
  "VAV": "w",
  "ZAYIN": "z",
  "HET": "ḥ",
  "TET": "ṭ",
  "YOD": "y",
  "FINAL_KAF": "ḵ",
  "KAF": "ḵ",
  "KAF_DAGESH": "k",
  "LAMED": "l",
  "FINAL_MEM": "m",
  "MEM": "m",
  "FINAL_NUN": "n",
  "NUN": "n",
  "SAMEKH": "s",
  "AYIN": "ʿ",
  "FINAL_PE": "p̄",
  "PE": "p̄",
  "PE_DAGESH": "p",
  "FINAL_TSADI": "ṣ",
  "TSADI": "ṣ",
  "QOF": "q",
  "RESH": "r",
  "SHIN": "š",
  "SIN": "ś",
  "TAV": "ṯ",
  "TAV_DAGESH": "t",
  "DIVINE_NAME": "yhwh",
  "SYLLABLE_SEPARATOR": "",
  "ADDITIONAL_FEATURES": [],
  "STRESS_MARKER": {
    "location": "",
    "mark": ""
  },
  "longVowels": true,
  "qametsQatan": true,
  "sqnmlvy": true,
  "wawShureq": true,
  "article": true
}
```

**Comment by charlesLoder** [comment]
> Would you be opposed to adding the Brill font as an option after Charis SIL but before Times New Roman for the output text area?

No opposition at all! I'll close this issue with that fix.

For the schema, I opened an issue in the [Node package](https://github.com/charlesLoder/hebrew-transliteration/issues/73).
